#!/usr/bin/env php
<?php declare(strict_types=1);
namespace Renamer;

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Output\ConsoleOutput;

use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;

use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\ErrorHandler\Debug;
use Symfony\Component\Filesystem\Filesystem;
use Symfony\Component\Console\Style\SymfonyStyle;

use Symfony\Component\Finder\Finder;
use Symfony\Component\Finder\SplFileInfo;

use function intval;

require_once __DIR__ . "/vendor/autoload_runtime.php";

return static function (Command $command): Command {
    set_time_limit(0);

    Debug::enable();

    $command->setName('anime-renamer');
    $command->setDescription('Rename a bunch of anime files to conform plex\'s crap');

    $command->setHelp(
        <<<'HELP'
        This tool is used to batch rename files so that it follows a logic of
        season and episodes in its title for a serie that is numbered in an
        absolute pattern.

        So if I have a serie that has 100+ episodes, with the following pattern :
        `My Serie E97 - foo bar.mkv`, and it belongs in the second season, which
        starts at episode 57, then I would use :

        `./renamer --start-from 1 --substract-episode 57 <path to dirctory> "My Serie E(?P<episode>\d+)" 2
        Which will rename all episodes starting the 57 in this form :
        `S2E1 (E57)`, `S2E2 (E58)`. ... and so on.

        You can also keep some info :

        `./renamer --start-from 1 --substract-episode 57 <path to dirctory> "My Serie E(?P<episode>\d+) - (?P<name>.*)\.mkv" 2`
        Which will rename all episodes starting the 57 in this form :
        `S2E1 (E57) - foo bar baz`, `S2E2 (E58) - baz bar`. ... and so on.
        HELP
    );

    $command
        ->addArgument('path', InputArgument::REQUIRED, 'Path to scan')
        ->addArgument('pattern', InputArgument::REQUIRED, 'Pattern to scan. There should be a `?P<episode>` at least in it.')
        ->addArgument('season', InputArgument::REQUIRED, 'Season to add (will prepend S%dE%d')
    ;

    $command
        ->addOption('dry-run', null, InputOption::VALUE_NONE, 'Do not do the actual renaming')
        ->addOption('substract-episode', null, InputOption::VALUE_REQUIRED, 'Substract this number to each episode number', 0)
        ->addOption('start-from', null, InputOption::VALUE_REQUIRED, 'Start from somewhere', 1)
    ;

    $command->setCode(function (InputInterface $input, ConsoleOutput $output) {
        $path = $input->getArgument('path');
        $pattern = $input->getArgument('pattern');
        $season = $input->getArgument('season');

        $progressSection = $output->section();
        $messagesSection = $output->section();

        $io = new SymfonyStyle($input, $messagesSection);

        if (!strpos($pattern, '?P<episode>')) {
            throw new \RuntimeException('Must have a episode match');
        }

        $finder = new Finder;

        $finder
            ->files()
            ->sortByName()
        ;

        $finder
            ->in($path)
            ->name("/{$pattern}/")
            ->depth(0);
        ;

        $filesystem = new Filesystem;

        $progress = new ProgressBar($progressSection);
        $progress->start(count($finder));

        $i = 0;

        /** @var SplFileInfo $file */
        foreach ($finder as $file) {
            preg_match("{{$input->getArgument('pattern')}}", $file->getBasename(), $matches);

            $episode = intval($matches['episode']) - intval($input->getOption('substract-episode')) + intval($input->getOption('start-from'));
            $name = "S{$season}E{$episode} (E{$matches['episode']}).{$file->getExtension()}";

            if (isset($matches['name'])) {
                $name = "S{$season}E{$episode} (E{$matches['episode']} - {$matches['name']}).{$file->getExtension()}";
            }

            if (!$input->getOption('dry-run')) {
                $filesystem->rename($file->getPathname(), "{$file->getPath()}/{$name}");
            }

            if ($i > 0 && $i % 5 === 0) {
                $messagesSection->clear(5);
            }

            ++$i;

            $io->comment("Renaming {$file->getBasename()} to {$name}");
            $progress->advance();
        }

        $progress->finish();
    });

    return $command;
};
